meme_list:
    path:     /
    defaults: { _controller: "MemeBundle:Meme:list" }

meme_show:
    path:     /{id}
    defaults: { _controller: "MemeBundle:Meme:show" }
    requirements:
        id: \d+

meme_random:
    path:     /losuj
    defaults: { _controller: "MemeBundle:Meme:random" }

meme_new:
    path:     /dodaj
    defaults: { _controller: "MemeBundle:Meme:new" }

meme_create:
    path:     /create
    defaults: { _controller: "MemeBundle:Meme:create" }
    methods:  POST

#meme_edit:
#    path:     /{id}/edit
#    defaults: { _controller: "MemeBundle:Meme:edit" }
#
#meme_update:
#    path:     /{id}/update
#    defaults: { _controller: "MemeBundle:Meme:update" }
#    methods:  [POST, PUT]
#
#meme_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "MemeBundle:Meme:delete" }
#    methods:  [POST, DELETE]
